"""Rename OvernightVehicle to ExtendedVehicle

Revision ID: 901612afef05
Revises: 
Create Date: 2025-04-23 05:50:10.781354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901612afef05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overnight_vehicle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overnight_vehicle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_category_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_category_id'], ['vehicle_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
