"""Add device_id, location, and site columns to VehicleEntry

Revision ID: cf7f29b6623d
Revises: de75d61f8034
Create Date: 2025-04-24 07:06:14.907017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7f29b6623d'
down_revision = 'de75d61f8034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('site', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_entry', schema=None) as batch_op:
        batch_op.drop_column('site')
        batch_op.drop_column('location')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
