"""Rename is_monthly_pass to is_overnight

Revision ID: d23c3ebc579a
Revises: 901612afef05
Create Date: 2025-04-23 05:51:49.667331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23c3ebc579a'
down_revision = '901612afef05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_overnight', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_monthly_pass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_monthly_pass', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_overnight')

    # ### end Alembic commands ###
