"""Add is_monthly_pass column to vehicle_category table

Revision ID: de75d61f8034
Revises: d23c3ebc579a
Create Date: 2025-04-23 07:19:58.914726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de75d61f8034'
down_revision = 'd23c3ebc579a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extended_vehicle')
    with op.batch_alter_table('vehicle_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_monthly_pass', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_overnight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_overnight', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_monthly_pass')

    op.create_table('extended_vehicle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_category_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_category_id'], ['vehicle_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
